apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-v1
  labels:
    app: nginx-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
      - name: nginx
        image: 178707647014.dkr.ecr.ap-south-1.amazonaws.com/nginx-eks:latest
        ports:
        - containerPort: 80