apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 2

  strategy:
    blueGreen:
      activeService: svc-blue
      previewService: svc-green
      autoPromotionEnabled: false   # manual approval

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 178707647014.dkr.ecr.ap-south-1.amazonaws.com/nginx-eks:latest
        ports:
        - containerPort: 80